version: '3'

services:
  # Hyperledger Fabric components
  ca.org1.example.com:
    image: hyperledger/fabric-ca:2.5
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.org1.example.com
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      - FABRIC_CA_SERVER_PORT=7054
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:17054
    ports:
      - '7054:7054'
      - '17054:17054'
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./fabric-config/ca:/etc/hyperledger/fabric-ca-server
    container_name: ca.org1.example.com
    networks:
      - mediblock-network

  orderer.example.com:
    image: hyperledger/fabric-orderer:2.5
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:17050
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    ports:
      - 7050:7050
      - 17050:17050
    volumes:
      - ./fabric-config/genesis.block:/var/hyperledger/orderer/genesis.block
      - ./fabric-config/msp/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
    container_name: orderer.example.com
    networks:
      - mediblock-network

  peer0.org1.example.com:
    image: hyperledger/fabric-peer:2.5
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=mediblock_mediblock-network
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.example.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:17051
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ./fabric-config/msp/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp:/etc/hyperledger/fabric/msp
      - ./fabric-config/msp/peerOrganizations/org1.example.com/users:/etc/hyperledger/msp/users
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7051:7051
      - 17051:17051
    container_name: peer0.org1.example.com
    networks:
      - mediblock-network

  # IPFS node
  ipfs:
    image: ipfs/kubo:latest
    ports:
      - '4001:4001'
      - '5001:5001'
      - '8080:8080'
    volumes:
      - ./ipfs_data:/data/ipfs
    environment:
      - IPFS_PROFILE=server
    container_name: ipfs-node
    networks:
      - mediblock-network

  # CLI for interacting with Fabric
  cli:
    image: hyperledger/fabric-tools:2.5
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ./chaincode:/opt/gopath/src/github.com/chaincode
      - ./fabric-config/msp/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp:/opt/gopath/src/github.com/hyperledger/fabric/peer/msp
    networks:
      - mediblock-network

networks:
  mediblock-network:
    name: mediblock-network
