apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "6"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"peer0-org1","namespace":"mediblock"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"peer0-org1"}},"template":{"metadata":{"labels":{"app":"peer0-org1"}},"spec":{"containers":[{"env":[{"name":"FABRIC_LOGGING_SPEC","value":"debug"},{"name":"CORE_PEER_ID","value":"peer0-org1"},{"name":"CORE_PEER_ADDRESS","value":"peer0-org1:7051"},{"name":"CORE_PEER_LISTENADDRESS","value":"0.0.0.0:7051"},{"name":"CORE_PEER_CHAINCODEADDRESS","value":"peer0-org1:7052"},{"name":"CORE_PEER_CHAINCODELISTENADDRESS","value":"0.0.0.0:7052"},{"name":"CORE_PEER_GOSSIP_BOOTSTRAP","value":"peer0-org1:7051"},{"name":"CORE_PEER_GOSSIP_EXTERNALENDPOINT","value":"peer0-org1:7051"},{"name":"CORE_PEER_LOCALMSPID","value":"MediBlockMSP"},{"name":"CORE_PEER_MSPCONFIGPATH","value":"/var/hyperledger/production/peer/msp"}],"image":"hyperledger/fabric-peer:2.5.4","name":"peer0-org1","ports":[{"containerPort":7051}],"volumeMounts":[{"mountPath":"/var/hyperledger/production","name":"empty-dir"}]}],"initContainers":[{"args":["mkdir -p /var/hyperledger/production/peer/msp/keystore \u0026\u0026 mkdir -p /var/hyperledger/production/peer/msp/cacerts \u0026\u0026 mkdir -p /var/hyperledger/production/peer/msp/signcerts \u0026\u0026 mkdir -p /var/hyperledger/production/peer/msp/admincerts \u0026\u0026 cp /msp-data/cacerts-ca.crt /var/hyperledger/production/peer/msp/cacerts/ca.crt \u0026\u0026 cp /msp-secret-data/key.pem /var/hyperledger/production/peer/msp/keystore/key.pem \u0026\u0026 cp /msp-data/signcerts-cert.pem /var/hyperledger/production/peer/msp/signcerts/cert.pem \u0026\u0026 cp /msp-data/admincerts-cert.pem /var/hyperledger/production/peer/msp/admincerts/cert.pem \u0026\u0026 mkdir -p /var/hyperledger/production/peer/msp/config \u0026\u0026 cp /msp-data/config.yaml /var/hyperledger/production/peer/msp/config/config.yaml \u0026\u0026 chmod -R 777 /var/hyperledger/production\n"],"command":["/bin/sh","-c"],"image":"busybox","name":"setup-folders","volumeMounts":[{"mountPath":"/msp-data","name":"msp-volume"},{"mountPath":"/msp-secret-data","name":"msp-secret-volume"},{"mountPath":"/var/hyperledger/production","name":"empty-dir"}]}],"volumes":[{"configMap":{"name":"peer0-org1-msp"},"name":"msp-volume"},{"name":"msp-secret-volume","secret":{"secretName":"peer0-org1-msp-secret"}},{"emptyDir":{},"name":"empty-dir"}]}}}}
  creationTimestamp: "2025-04-05T18:37:36Z"
  generation: 6
  name: peer0-org1
  namespace: mediblock
  resourceVersion: "248931"
  uid: 206f6b8f-b807-46dc-9e82-3f0e23ade2f0
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: peer0-org1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-04-06T02:25:58+06:00"
      creationTimestamp: null
      labels:
        app: peer0-org1
    spec:
      containers:
      - env:
        - name: FABRIC_LOGGING_SPEC
          value: debug
        - name: CORE_PEER_ID
          value: peer0-org1
        - name: CORE_PEER_ADDRESS
          value: peer0-org1:7051
        - name: CORE_PEER_LISTENADDRESS
          value: 0.0.0.0:7051
        - name: CORE_PEER_CHAINCODEADDRESS
          value: peer0-org1:7052
        - name: CORE_PEER_CHAINCODELISTENADDRESS
          value: 0.0.0.0:7052
        - name: CORE_PEER_GOSSIP_BOOTSTRAP
          value: peer0-org1:7051
        - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
          value: peer0-org1:7051
        - name: CORE_PEER_LOCALMSPID
          value: MediBlockMSP
        - name: CORE_PEER_MSPCONFIGPATH
          value: /var/hyperledger/production/peer/msp
        image: hyperledger/fabric-peer:2.5.4
        imagePullPolicy: IfNotPresent
        name: peer0-org1
        ports:
        - containerPort: 7051
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/hyperledger/production
          name: empty-dir
      dnsPolicy: ClusterFirst
      initContainers:
      - args:
        - |
          mkdir -p /var/hyperledger/production/peer/msp/keystore && mkdir -p /var/hyperledger/production/peer/msp/cacerts && mkdir -p /var/hyperledger/production/peer/msp/signcerts && mkdir -p /var/hyperledger/production/peer/msp/admincerts && cp /msp-data/cacerts-ca.crt /var/hyperledger/production/peer/msp/cacerts/ca.crt && cp /msp-secret-data/key.pem /var/hyperledger/production/peer/msp/keystore/key.pem && cp /msp-data/signcerts-cert.pem /var/hyperledger/production/peer/msp/signcerts/cert.pem && cp /msp-data/admincerts-cert.pem /var/hyperledger/production/peer/msp/admincerts/cert.pem && mkdir -p /var/hyperledger/production/peer/msp/config && cp /msp-data/config.yaml /var/hyperledger/production/peer/msp/config/config.yaml && chmod -R 777 /var/hyperledger/production
        command:
        - /bin/sh
        - -c
        image: busybox
        imagePullPolicy: Always
        name: setup-folders
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /msp-data
          name: msp-volume
        - mountPath: /msp-secret-data
          name: msp-secret-volume
        - mountPath: /var/hyperledger/production
          name: empty-dir
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: peer0-org1-msp
        name: msp-volume
      - name: msp-secret-volume
        secret:
          defaultMode: 420
          secretName: peer0-org1-msp-secret
      - emptyDir: {}
        name: empty-dir
status:
  conditions:
  - lastTransitionTime: "2025-04-05T18:37:36Z"
    lastUpdateTime: "2025-04-05T18:37:36Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2025-04-05T20:36:27Z"
    lastUpdateTime: "2025-04-05T20:36:27Z"
    message: ReplicaSet "peer0-org1-949d9b745" has timed out progressing.
    reason: ProgressDeadlineExceeded
    status: "False"
    type: Progressing
  observedGeneration: 6
  replicas: 2
  unavailableReplicas: 2
  updatedReplicas: 1
