apiVersion: v1
kind: ConfigMap
metadata:
  name: mediblock-config
  namespace: mediblock
data:
  # Python service configuration
  IPFS_API_URL: "http://ipfs:5001/api/v0"
  GO_SERVICE_URL: "http://go-service:8081/api"
  PYTHON_SERVICE_PORT: "5000"
  
  # Go service configuration
  FABRIC_NETWORK_URL: "peer0.org1.example.com:7051"
  CHAINCODE_ID: "ehrmanager"
  CHANNEL_ID: "mychannel"
  MSP_ID: "Org1MSP"
  
  # NextJS frontend configuration
  NEXT_PUBLIC_API_URL: "http://python-service:5000/api" 