apiVersion: v1
kind: ConfigMap
metadata:
  name: fabric-config
  namespace: mediblock
data:
  core.yaml: |
    peer:
      id: peer0
      networkId: mediblock
      listenAddress: 0.0.0.0:7051
      chaincodeListenAddress: 0.0.0.0:7052
      address: 0.0.0.0:7051
      gossip:
        bootstrap: peer0-org1:7051
        endpoint: peer0-org1:7051
        externalEndpoint: peer0-org1:7051
      tls:
        enabled: false
      mspConfigPath: /var/hyperledger/production/peer/msp
    ledger:
      state:
        stateDatabase: goleveldb
      history:
        enableHistoryDatabase: true
    chaincode:
      logging:
        level: info
    
  orderer.yaml: |
    General:
      ListenAddress: 0.0.0.0
      ListenPort: 7050
      TLS:
        Enabled: false
      LogLevel: info
      GenesisMethod: none
      LocalMSPDir: /var/hyperledger/production/orderer/msp
      LocalMSPID: MediBlockMSP
    FileLedger:
      Location: /var/hyperledger/production/orderer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: orderer-msp
  namespace: mediblock
data:
  cacerts-ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIICOzCCAeCgAwIBAgIJAK2IibHURDcmMAoGCCqGSM49BAMCMH8xCzAJBgNVBAYT
    AlVTMRMwEQYDVQQIDApDYWxpZm9ybmlhMRYwFAYDVQQHDA1TYW4gRnJhbmNpc2Nv
    MRIwEAYDVQQKDAlNZWRpQmxvY2sxGzAZBgNVBAsMEkh5cGVybGVkZ2VyIEZhYnJp
    YzESMBAGA1UEAwwJZmFicmljLWNhMB4XDTI1MDMzMDEyMTQyMFoXDTM1MDMyODEy
    MTQyMFowfzELMAkGA1UEBhMCVVMxEzARBgNVBAgMCkNhbGlmb3JuaWExFjAUBgNV
    BAcMDVNhbiBGcmFuY2lzY28xEjAQBgNVBAoMCU1lZGlCbG9jazEbMBkGA1UECwwS
    SHlwZXJsZWRnZXIgRmFicmljMRIwEAYDVQQDDAlmYWJyaWMtY2EwWTATBgcqhkjO
    PQIBBggqhkjOPQMBBwNCAASVpz56AYQ9K9I97BfBW9e/1XT3M6Zn+YkzqHP+WJgU
    kGDlSaD86n7qf2L8Lxcw5e/INcysbbsCRbWBJfWYrb9Zo0UwQzASBgNVHRMBAf8E
    CDAGAQH/AgEBMA4GA1UdDwEB/wQEAwIBBjAdBgNVHQ4EFgQUchsOBiFBrZXaTy9k
    VGfqLBnYiekwCgYIKoZIzj0EAwIDSQAwRgIhAKvz82TmHCUPIhWOSPGWG/aP0/Sn
    TAuWbV67vgQHCwbjAiEA26Nyhvg8UC8sMf95vWx61Bva1kq4wTV7pC2nX0eBWsY=
    -----END CERTIFICATE-----
  keystore-key.pem: |
    -----BEGIN EC PRIVATE KEY-----
    MHcCAQEEIPQE3nfaDgE/z7vrLyrAnsOMB64AjAghmKSvZriJMVb2oAoGCCqGSM49
    AwEHoUQDQgAEtk3SAGNoEey4nJVQxUOJ07IsfpPPMchBbYZZojm+t193/2/YnbDy
    PzCJknSXZYGLM/lw2g0fSbazsHohCfmKaw==
    -----END EC PRIVATE KEY-----
  signcerts-cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIICszCCAligAwIBAgIJAMWPdDLhnb+vMAoGCCqGSM49BAMCMH8xCzAJBgNVBAYT
    AlVTMRMwEQYDVQQIDApDYWxpZm9ybmlhMRYwFAYDVQQHDA1TYW4gRnJhbmNpc2Nv
    MRIwEAYDVQQKDAlNZWRpQmxvY2sxGzAZBgNVBAsMEkh5cGVybGVkZ2VyIEZhYnJp
    YzESMBAGA1UEAwwJZmFicmljLWNhMB4XDTI1MDMzMDEyMTQyMFoXDTM1MDMyODEy
    MTQyMFowfzELMAkGA1UEBhMCVVMxEzARBgNVBAgMCkNhbGlmb3JuaWExFjAUBgNV
    BAcMDVNhbiBGcmFuY2lzY28xEjAQBgNVBAoMCU1lZGlCbG9jazEbMBkGA1UECwwS
    SHlwZXJsZWRnZXIgRmFicmljMRIwEAYDVQQDDAlmYWJyaWMtY2EwWTATBgcqhkjO
    PQIBBggqhkjOPQMBBwNCAAS2TdIAY2gR7LiclVDFQ4nTsix+k88xyEFthlmiOb63
    X3f/b9idsPI/MImSdJdlgYsz+XDaDR9JtrOweiEJ+Ypro4G8MIG5MA4GA1UdDwEB
    /wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/
    BAIwADAdBgNVHQ4EFgQUf1ckT8xinVLVta9Z5dyVsbVioi0wHwYDVR0jBBgwFoAU
    chsOBiFBrZXaTy9kVGfqLBnYiekwOgYDVR0RBDMwMYIVb3JkZXJlci5tZWRpYmxv
    Y2suY29tggdvcmRlcmVygglsb2NhbGhvc3SHBH8AAAEwCgYIKoZIzj0EAwIDSQAw
    RgIhAMg/06Afy05L6sVarh+Wc8O5CVQs4Km33fHDJ9tg3k9BAiEAwXRrzPF6he1N
    jUsnvwnVbTLjdRotXRphJMShIQNxuVU=
    -----END CERTIFICATE-----
  admincerts-cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIICazCCAhCgAwIBAgIJAMWPdDLhnb+xMAoGCCqGSM49BAMCMH8xCzAJBgNVBAYT
    AlVTMRMwEQYDVQQIDApDYWxpZm9ybmlhMRYwFAYDVQQHDA1TYW4gRnJhbmNpc2Nv
    MRIwEAYDVQQKDAlNZWRpQmxvY2sxGzAZBgNVBAsMEkh5cGVybGVkZ2VyIEZhYnJp
    YzESMBAGA1UEAwwJZmFicmljLWNhMB4XDTI1MDMzMDEyMTQyMFoXDTM1MDMyODEy
    MTQyMFowfzELMAkGA1UEBhMCVVMxEzARBgNVBAgMCkNhbGlmb3JuaWExFjAUBgNV
    BAcMDVNhbiBGcmFuY2lzY28xEjAQBgNVBAoMCU1lZGlCbG9jazEbMBkGA1UECwwS
    SHlwZXJsZWRnZXIgRmFicmljMRIwEAYDVQQDDAlmYWJyaWMtY2EwWTATBgcqhkjO
    PQIBBggqhkjOPQMBBwNCAATfX9QetnpWNMUAFPzJaXp9Z/n+C9mHMwhRFmJxfk+O
    AZemHwvkBW6E39GZJ9PZvSMaNn3nm0EAGbTorvwSvEkMo3UwczAOBgNVHQ8BAf8E
    BAMCB4AwEwYDVR0lBAwwCgYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4E
    FgQUowwl7k85UDPvVdNMIr2Xow3klrwwHwYDVR0jBBgwFoAUchsOBiFBrZXaTy9k
    VGfqLBnYiekwCgYIKoZIzj0EAwIDSQAwRgIhAPFvedcEVcCBSFI2uLcrjP4JkjWK
    acJ54tQ8DwyLdNXIAiEA/Ydu2WeZrThBqHXWpu8qeopZ+6d99SLABf8yibEoLdQ=
    -----END CERTIFICATE-----
  config.yaml: |
    NodeOUs:
      Enable: false
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: peer0-org1-msp
  namespace: mediblock
data:
  cacerts-ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIICOzCCAeCgAwIBAgIJAK2IibHURDcmMAoGCCqGSM49BAMCMH8xCzAJBgNVBAYT
    AlVTMRMwEQYDVQQIDApDYWxpZm9ybmlhMRYwFAYDVQQHDA1TYW4gRnJhbmNpc2Nv
    MRIwEAYDVQQKDAlNZWRpQmxvY2sxGzAZBgNVBAsMEkh5cGVybGVkZ2VyIEZhYnJp
    YzESMBAGA1UEAwwJZmFicmljLWNhMB4XDTI1MDMzMDEyMTQyMFoXDTM1MDMyODEy
    MTQyMFowfzELMAkGA1UEBhMCVVMxEzARBgNVBAgMCkNhbGlmb3JuaWExFjAUBgNV
    BAcMDVNhbiBGcmFuY2lzY28xEjAQBgNVBAoMCU1lZGlCbG9jazEbMBkGA1UECwwS
    SHlwZXJsZWRnZXIgRmFicmljMRIwEAYDVQQDDAlmYWJyaWMtY2EwWTATBgcqhkjO
    PQIBBggqhkjOPQMBBwNCAASVpz56AYQ9K9I97BfBW9e/1XT3M6Zn+YkzqHP+WJgU
    kGDlSaD86n7qf2L8Lxcw5e/INcysbbsCRbWBJfWYrb9Zo0UwQzASBgNVHRMBAf8E
    CDAGAQH/AgEBMA4GA1UdDwEB/wQEAwIBBjAdBgNVHQ4EFgQUchsOBiFBrZXaTy9k
    VGfqLBnYiekwCgYIKoZIzj0EAwIDSQAwRgIhAKvz82TmHCUPIhWOSPGWG/aP0/Sn
    TAuWbV67vgQHCwbjAiEA26Nyhvg8UC8sMf95vWx61Bva1kq4wTV7pC2nX0eBWsY=
    -----END CERTIFICATE-----
  keystore-key.pem: |
    -----BEGIN EC PRIVATE KEY-----
    MHcCAQEEIC9DeHvUB7dqztkY/uLeCX7Pqu+JFMeMmS04QfkmHo0/oAoGCCqGSM49
    AwEHoUQDQgAEKi2HZ/pDll7Vb4qwtB3h8yWEQeKCL2/wqvS+OOuXmjCHskKRqkrJ
    P0fq9/87bu/gp/TO3F13/sL7h0zkNSS8GQ==
    -----END EC PRIVATE KEY-----
  signcerts-cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIICtzCCAl6gAwIBAgIJAMWPdDLhnb+wMAoGCCqGSM49BAMCMH8xCzAJBgNVBAYT
    AlVTMRMwEQYDVQQIDApDYWxpZm9ybmlhMRYwFAYDVQQHDA1TYW4gRnJhbmNpc2Nv
    MRIwEAYDVQQKDAlNZWRpQmxvY2sxGzAZBgNVBAsMEkh5cGVybGVkZ2VyIEZhYnJp
    YzESMBAGA1UEAwwJZmFicmljLWNhMB4XDTI1MDMzMDEyMTQyMFoXDTM1MDMyODEy
    MTQyMFowfzELMAkGA1UEBhMCVVMxEzARBgNVBAgMCkNhbGlmb3JuaWExFjAUBgNV
    BAcMDVNhbiBGcmFuY2lzY28xEjAQBgNVBAoMCU1lZGlCbG9jazEbMBkGA1UECwwS
    SHlwZXJsZWRnZXIgRmFicmljMRIwEAYDVQQDDAlmYWJyaWMtY2EwWTATBgcqhkjO
    PQIBBggqhkjOPQMBBwNCAAQqLYdn+kOWXtVvirC0HeHzJYRB4oIvb/Cq9L4465ea
    MIeyQpGqSsk/R+r3/ztu7+Cn9M7cXXf+wvuHTOQ1JLwZo4HCMIG/MA4GA1UdDwEB
    /wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/
    BAIwADAdBgNVHQ4EFgQU/NqqhvlZB0VD5B96oaT5Ah94IX8wHwYDVR0jBBgwFoAU
    chsOBiFBrZXaTy9kVGfqLBnYiekwQAYDVR0RBDkwN4IYcGVlcjAub3JnMS5tZWRp
    YmxvY2suY29tggpwZWVyMC1vcmcxgglsb2NhbGhvc3SHBH8AAAEwCgYIKoZIzj0E
    AwIDRwAwRAIgKUOqTBmUX2d6VgTwkM3P/9IXDBrxCAXyoaOIGZdRJooCIDAmG+0w
    BXXBtiZcT6qtPyC6Eoad/S01GMXspVQiBOtc
    -----END CERTIFICATE-----
  admincerts-cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIICazCCAhCgAwIBAgIJAMWPdDLhnb+xMAoGCCqGSM49BAMCMH8xCzAJBgNVBAYT
    AlVTMRMwEQYDVQQIDApDYWxpZm9ybmlhMRYwFAYDVQQHDA1TYW4gRnJhbmNpc2Nv
    MRIwEAYDVQQKDAlNZWRpQmxvY2sxGzAZBgNVBAsMEkh5cGVybGVkZ2VyIEZhYnJp
    YzESMBAGA1UEAwwJZmFicmljLWNhMB4XDTI1MDMzMDEyMTQyMFoXDTM1MDMyODEy
    MTQyMFowfzELMAkGA1UEBhMCVVMxEzARBgNVBAgMCkNhbGlmb3JuaWExFjAUBgNV
    BAcMDVNhbiBGcmFuY2lzY28xEjAQBgNVBAoMCU1lZGlCbG9jazEbMBkGA1UECwwS
    SHlwZXJsZWRnZXIgRmFicmljMRIwEAYDVQQDDAlmYWJyaWMtY2EwWTATBgcqhkjO
    PQIBBggqhkjOPQMBBwNCAATfX9QetnpWNMUAFPzJaXp9Z/n+C9mHMwhRFmJxfk+O
    AZemHwvkBW6E39GZJ9PZvSMaNn3nm0EAGbTorvwSvEkMo3UwczAOBgNVHQ8BAf8E
    BAMCB4AwEwYDVR0lBAwwCgYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4E
    FgQUowwl7k85UDPvVdNMIr2Xow3klrwwHwYDVR0jBBgwFoAUchsOBiFBrZXaTy9k
    VGfqLBnYiekwCgYIKoZIzj0EAwIDSQAwRgIhAPFvedcEVcCBSFI2uLcrjP4JkjWK
    acJ54tQ8DwyLdNXIAiEA/Ydu2WeZrThBqHXWpu8qeopZ+6d99SLABf8yibEoLdQ=
    -----END CERTIFICATE-----
  config.yaml: |
    NodeOUs:
      Enable: false
