apiVersion: v1
kind: ConfigMap
metadata:
  name: fabric-config
  namespace: mediblock
data:
  core.yaml: |
    peer:
      id: peer0
      networkId: mediblock
      listenAddress: 0.0.0.0:7051
      chaincodeListenAddress: 0.0.0.0:7052
      address: 0.0.0.0:7051
      gossip:
        bootstrap: peer0-org1:7051
        endpoint: peer0-org1:7051
        externalEndpoint: peer0-org1:7051
      tls:
        enabled: false
    ledger:
      state:
        stateDatabase: goleveldb
    chaincode:
      logging:
        level: info
    
  orderer.yaml: |
    General:
      ListenAddress: 0.0.0.0
      ListenPort: 7050
      TLS:
        Enabled: false
      LogLevel: info
      GenesisMethod: file
      GenesisFile: /var/hyperledger/fabric/config/genesis.block
      LocalMSPDir: /var/hyperledger/fabric/msp
      LocalMSPID: OrdererMSP
    FileLedger:
      Location: /var/hyperledger/fabric/data
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: orderer-msp
  namespace: mediblock
data:
  cacerts-ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIICWjCCAf+gAwIBAgIJAOYMbycoiGsZMAoGCCqGSM49BAMCMH8xCzAJBgNVBAYT
    AlVTMRMwEQYDVQQIDApDYWxpZm9ybmlhMRYwFAYDVQQHDA1TYW4gRnJhbmNpc2Nv
    MRIwEAYDVQQKDAlNZWRpQmxvY2sxGzAZBgNVBAsMEkh5cGVybGVkZ2VyIEZhYnJp
    YzESMBAGA1UEAwwJZmFicmljLWNhMB4XDTI1MDMyOTIyNDk0NFoXDTM1MDMyNzIy
    NDk0NFowfzELMAkGA1UEBhMCVVMxEzARBgNVBAgMCkNhbGlmb3JuaWExFjAUBgNV
    BAcMDVNhbiBGcmFuY2lzY28xEjAQBgNVBAoMCU1lZGlCbG9jazEbMBkGA1UECwwS
    SHlwZXJsZWRnZXIgRmFicmljMRIwEAYDVQQDDAlmYWJyaWMtY2EwWTATBgcqhkjO
    PQIBBggqhkjOPQMBBwNCAAQKwxkOleGJqWyr7haPGIlKOCsKscGvsMwTQzA4KBOw
    6BRPjdrVgzFVGpNk/Ag3I89lMt6lKnd4MeuEWI+PrfRxo2QwYjAOBgNVHQ8BAf8E
    BAMCAaYwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMBIGA1UdEwEB/wQI
    MAYBAf8CAQEwHQYDVR0OBBYEFKetRJm7PqEp/UrmEIWtxfZY9dJ5MAoGCCqGSM49
    BAMCA0kAMEYCIQCPjk2Hd4MOhE5it84jlFSsHhLG8sEcflCL9gSCYSRjgwIhAMUw
    rZU1zztgrpWHWdtjSv+G3eKpUgfMv+0gwLFMd+xo
    -----END CERTIFICATE-----
  keystore-key.pem: |
    -----BEGIN EC PRIVATE KEY-----
    MHcCAQEEIA/nzyQXHMSeeDvVMA7Fx92808LMfrcQYb81/4dGxdRjoAoGCCqGSM49
    AwEHoUQDQgAEeuB++mdWjPpkAUAozBh7wU8Sjx24bcadQDDxgvHwaoTLhlLNdp3p
    wmInUX7ELgc/PiOzRDA+TIvqFOjw7ma+rQ==
    -----END EC PRIVATE KEY-----
  signcerts-cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIICsjCCAligAwIBAgIJAIBzrc0/K3KHMAoGCCqGSM49BAMCMH8xCzAJBgNVBAYT
    AlVTMRMwEQYDVQQIDApDYWxpZm9ybmlhMRYwFAYDVQQHDA1TYW4gRnJhbmNpc2Nv
    MRIwEAYDVQQKDAlNZWRpQmxvY2sxGzAZBgNVBAsMEkh5cGVybGVkZ2VyIEZhYnJp
    YzESMBAGA1UEAwwJZmFicmljLWNhMB4XDTI1MDMyOTIyNDk0NFoXDTM1MDMyNzIy
    NDk0NFowfzELMAkGA1UEBhMCVVMxEzARBgNVBAgMCkNhbGlmb3JuaWExFjAUBgNV
    BAcMDVNhbiBGcmFuY2lzY28xEjAQBgNVBAoMCU1lZGlCbG9jazEbMBkGA1UECwwS
    SHlwZXJsZWRnZXIgRmFicmljMRIwEAYDVQQDDAlmYWJyaWMtY2EwWTATBgcqhkjO
    PQIBBggqhkjOPQMBBwNCAAR64H76Z1aM+mQBQCjMGHvBTxKPHbhtxp1AMPGC8fBq
    hMuGUs12nenCYidRfsQuBz8+I7NEMD5Mi+oU6PDuZr6to4G8MIG5MA4GA1UdDwEB
    /wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/
    BAIwADAdBgNVHQ4EFgQU4qzCWeijLceb+99pOqn+a94LOHUwHwYDVR0jBBgwFoAU
    p61Embs+oSn9SuYQha3F9lj10nkwOgYDVR0RBDMwMYIVb3JkZXJlci5tZWRpYmxv
    Y2suY29tggdvcmRlcmVygglsb2NhbGhvc3SHBH8AAAEwCgYIKoZIzj0EAwIDSAAw
    RQIhALSd17wZ6bbmJM2CS6+r5dtfpfjUjSHsuW11bftTtpF0AiAGDbdLAhX4Jk5x
    OND5WspAqSJ0OeynRQwy0jvPAfk7IQ==
    -----END CERTIFICATE-----
  admincerts-cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIICajCCAhCgAwIBAgIJAIBzrc0/K3KJMAoGCCqGSM49BAMCMH8xCzAJBgNVBAYT
    AlVTMRMwEQYDVQQIDApDYWxpZm9ybmlhMRYwFAYDVQQHDA1TYW4gRnJhbmNpc2Nv
    MRIwEAYDVQQKDAlNZWRpQmxvY2sxGzAZBgNVBAsMEkh5cGVybGVkZ2VyIEZhYnJp
    YzESMBAGA1UEAwwJZmFicmljLWNhMB4XDTI1MDMyOTIyNDk0NFoXDTM1MDMyNzIy
    NDk0NFowfzELMAkGA1UEBhMCVVMxEzARBgNVBAgMCkNhbGlmb3JuaWExFjAUBgNV
    BAcMDVNhbiBGcmFuY2lzY28xEjAQBgNVBAoMCU1lZGlCbG9jazEbMBkGA1UECwwS
    SHlwZXJsZWRnZXIgRmFicmljMRIwEAYDVQQDDAlmYWJyaWMtY2EwWTATBgcqhkjO
    PQIBBggqhkjOPQMBBwNCAATVmHhnHk3yyt8SXu81cvoGc5WYQkOFb4R3G8ztuOm6
    LY+P9q3KTYvxdZiZWlLqO9M40QIsMszAEA0mTpbsG/gWo3UwczAOBgNVHQ8BAf8E
    BAMCB4AwEwYDVR0lBAwwCgYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4E
    FgQUagQPXcjBRCtsWXE1P45NFVSmRUYwHwYDVR0jBBgwFoAUp61Embs+oSn9SuYQ
    ha3F9lj10nkwCgYIKoZIzj0EAwIDSAAwRQIgfedCRTMDQRdLShuJUCquefOZj8UB
    cazNTWov9Tff5noCIQC2isdRNfKFQXI9OJ70Kp44sYFgISV5Jkoqo0kLOXuxSg==
    -----END CERTIFICATE-----
  config.yaml: |
    NodeOUs:
      Enable: false
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: peer0-org1-msp
  namespace: mediblock
data:
  cacerts-ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIICWjCCAf+gAwIBAgIJAOYMbycoiGsZMAoGCCqGSM49BAMCMH8xCzAJBgNVBAYT
    AlVTMRMwEQYDVQQIDApDYWxpZm9ybmlhMRYwFAYDVQQHDA1TYW4gRnJhbmNpc2Nv
    MRIwEAYDVQQKDAlNZWRpQmxvY2sxGzAZBgNVBAsMEkh5cGVybGVkZ2VyIEZhYnJp
    YzESMBAGA1UEAwwJZmFicmljLWNhMB4XDTI1MDMyOTIyNDk0NFoXDTM1MDMyNzIy
    NDk0NFowfzELMAkGA1UEBhMCVVMxEzARBgNVBAgMCkNhbGlmb3JuaWExFjAUBgNV
    BAcMDVNhbiBGcmFuY2lzY28xEjAQBgNVBAoMCU1lZGlCbG9jazEbMBkGA1UECwwS
    SHlwZXJsZWRnZXIgRmFicmljMRIwEAYDVQQDDAlmYWJyaWMtY2EwWTATBgcqhkjO
    PQIBBggqhkjOPQMBBwNCAAQKwxkOleGJqWyr7haPGIlKOCsKscGvsMwTQzA4KBOw
    6BRPjdrVgzFVGpNk/Ag3I89lMt6lKnd4MeuEWI+PrfRxo2QwYjAOBgNVHQ8BAf8E
    BAMCAaYwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMBIGA1UdEwEB/wQI
    MAYBAf8CAQEwHQYDVR0OBBYEFKetRJm7PqEp/UrmEIWtxfZY9dJ5MAoGCCqGSM49
    BAMCA0kAMEYCIQCPjk2Hd4MOhE5it84jlFSsHhLG8sEcflCL9gSCYSRjgwIhAMUw
    rZU1zztgrpWHWdtjSv+G3eKpUgfMv+0gwLFMd+xo
    -----END CERTIFICATE-----
  keystore-key.pem: |
    -----BEGIN EC PRIVATE KEY-----
    MHcCAQEEICvOF2UK2gqJqIv0hKtbblfdQ9y+4ZThLWwr50GNZIDpoAoGCCqGSM49
    AwEHoUQDQgAEYjbjs8bE3T8nacSzCh936NA0V+fSsu7xzX5zsQtwRT66v/qNJDhv
    Mpvwa9AmvmNVNhKakfUwXYMsYGMNZhZYxQ==
    -----END EC PRIVATE KEY-----
  signcerts-cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIICtzCCAl6gAwIBAgIJAIBzrc0/K3KIMAoGCCqGSM49BAMCMH8xCzAJBgNVBAYT
    AlVTMRMwEQYDVQQIDApDYWxpZm9ybmlhMRYwFAYDVQQHDA1TYW4gRnJhbmNpc2Nv
    MRIwEAYDVQQKDAlNZWRpQmxvY2sxGzAZBgNVBAsMEkh5cGVybGVkZ2VyIEZhYnJp
    YzESMBAGA1UEAwwJZmFicmljLWNhMB4XDTI1MDMyOTIyNDk0NFoXDTM1MDMyNzIy
    NDk0NFowfzELMAkGA1UEBhMCVVMxEzARBgNVBAgMCkNhbGlmb3JuaWExFjAUBgNV
    BAcMDVNhbiBGcmFuY2lzY28xEjAQBgNVBAoMCU1lZGlCbG9jazEbMBkGA1UECwwS
    SHlwZXJsZWRnZXIgRmFicmljMRIwEAYDVQQDDAlmYWJyaWMtY2EwWTATBgcqhkjO
    PQIBBggqhkjOPQMBBwNCAARiNuOzxsTdPydpxLMKH3fo0DRX59Ky7vHNfnOxC3BF
    Prq/+o0kOG8ym/Br0Ca+Y1U2EpqR9TBdgyxgYw1mFljFo4HCMIG/MA4GA1UdDwEB
    /wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/
    BAIwADAdBgNVHQ4EFgQUGDKPC99DqE4p1Kf6jpaW4YLmuoQwHwYDVR0jBBgwFoAU
    p61Embs+oSn9SuYQha3F9lj10nkwQAYDVR0RBDkwN4IYcGVlcjAub3JnMS5tZWRp
    YmxvY2suY29tggpwZWVyMC1vcmcxgglsb2NhbGhvc3SHBH8AAAEwCgYIKoZIzj0E
    AwIDRwAwRAIgH39RKceB6S8eFCOSRtrDRwdVV/3bfsrrJggeeKezPgMCIC5aDGLb
    X71zqBFFRgwVTpMIL2AqAEWYTHkXyDNrtTlR
    -----END CERTIFICATE-----
  admincerts-cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIICajCCAhCgAwIBAgIJAIBzrc0/K3KJMAoGCCqGSM49BAMCMH8xCzAJBgNVBAYT
    AlVTMRMwEQYDVQQIDApDYWxpZm9ybmlhMRYwFAYDVQQHDA1TYW4gRnJhbmNpc2Nv
    MRIwEAYDVQQKDAlNZWRpQmxvY2sxGzAZBgNVBAsMEkh5cGVybGVkZ2VyIEZhYnJp
    YzESMBAGA1UEAwwJZmFicmljLWNhMB4XDTI1MDMyOTIyNDk0NFoXDTM1MDMyNzIy
    NDk0NFowfzELMAkGA1UEBhMCVVMxEzARBgNVBAgMCkNhbGlmb3JuaWExFjAUBgNV
    BAcMDVNhbiBGcmFuY2lzY28xEjAQBgNVBAoMCU1lZGlCbG9jazEbMBkGA1UECwwS
    SHlwZXJsZWRnZXIgRmFicmljMRIwEAYDVQQDDAlmYWJyaWMtY2EwWTATBgcqhkjO
    PQIBBggqhkjOPQMBBwNCAATVmHhnHk3yyt8SXu81cvoGc5WYQkOFb4R3G8ztuOm6
    LY+P9q3KTYvxdZiZWlLqO9M40QIsMszAEA0mTpbsG/gWo3UwczAOBgNVHQ8BAf8E
    BAMCB4AwEwYDVR0lBAwwCgYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4E
    FgQUagQPXcjBRCtsWXE1P45NFVSmRUYwHwYDVR0jBBgwFoAUp61Embs+oSn9SuYQ
    ha3F9lj10nkwCgYIKoZIzj0EAwIDSAAwRQIgfedCRTMDQRdLShuJUCquefOZj8UB
    cazNTWov9Tff5noCIQC2isdRNfKFQXI9OJ70Kp44sYFgISV5Jkoqo0kLOXuxSg==
    -----END CERTIFICATE-----
  config.yaml: |
    NodeOUs:
      Enable: false
