---
apiVersion: v1
kind: Service
metadata:
  name: ca-org1
  namespace: mediblock
spec:
  selector:
    app: ca-org1
  ports:
  - name: ca-port
    port: 7054
    targetPort: 7054
  - name: operations
    port: 17054
    targetPort: 17054
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ca-org1
  namespace: mediblock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ca-org1
  template:
    metadata:
      labels:
        app: ca-org1
    spec:
      containers:
      - name: ca-org1
        image: hyperledger/fabric-ca:latest
        env:
        - name: FABRIC_CA_HOME
          value: /etc/hyperledger/fabric-ca-server
        - name: FABRIC_CA_SERVER_CA_NAME
          value: ca.org1.example.com
        - name: FABRIC_CA_SERVER_TLS_ENABLED
          value: "false"
        - name: FABRIC_CA_SERVER_PORT
          value: "7054"
        - name: FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS
          value: 0.0.0.0:17054
        ports:
        - containerPort: 7054
        - containerPort: 17054
        command: ["sh", "-c", "fabric-ca-server start -b admin:adminpw -d"]
        volumeMounts:
        - name: ca-config
          mountPath: /etc/hyperledger/fabric-ca-server
      volumes:
      - name: ca-config
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: orderer
  namespace: mediblock
spec:
  selector:
    app: orderer
  ports:
  - name: orderer-port
    port: 7050
    targetPort: 7050
  - name: operations
    port: 17050
    targetPort: 17050
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderer
  namespace: mediblock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderer
  template:
    metadata:
      labels:
        app: orderer
    spec:
      volumes:
        - name: msp-volume
          configMap:
            name: orderer-msp
        - name: msp-secret-volume
          secret:
            secretName: orderer-msp-secret
        - name: empty-dir
          emptyDir: {}
      initContainers:
        - name: setup-folders
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - |
              mkdir -p /var/hyperledger/production/orderer/msp/keystore && mkdir -p /var/hyperledger/production/orderer/msp/cacerts && mkdir -p /var/hyperledger/production/orderer/msp/signcerts && mkdir -p /var/hyperledger/production/orderer/msp/admincerts && cp /msp-data/cacerts-ca.crt /var/hyperledger/production/orderer/msp/cacerts/ca.crt && cp /msp-secret-data/key.pem /var/hyperledger/production/orderer/msp/keystore/key.pem && cp /msp-data/signcerts-cert.pem /var/hyperledger/production/orderer/msp/signcerts/cert.pem && cp /msp-data/admincerts-cert.pem /var/hyperledger/production/orderer/msp/admincerts/cert.pem && chmod -R 777 /var/hyperledger/production
          volumeMounts:
            - name: msp-volume
              mountPath: /msp-data
            - name: msp-secret-volume
              mountPath: /msp-secret-data
            - name: empty-dir
              mountPath: /var/hyperledger/production
      containers:
        - name: orderer
          image: hyperledger/fabric-orderer:2.5.4
          command: ["orderer"]
          ports:
            - containerPort: 7050
          env:
            - name: FABRIC_LOGGING_SPEC
              value: "debug"
            - name: ORDERER_GENERAL_LISTENADDRESS
              value: "0.0.0.0"
            - name: ORDERER_GENERAL_GENESISMETHOD
              value: "none"
            - name: ORDERER_GENERAL_CHANNELPARTICIPATION_ENABLED
              value: "true"
            - name: ORDERER_GENERAL_LOCALMSPID
              value: "MediBlockMSP"
            - name: ORDERER_GENERAL_LOCALMSPDIR
              value: "/var/hyperledger/production/orderer/msp"
          volumeMounts:
            - name: empty-dir
              mountPath: /var/hyperledger/production
---
apiVersion: v1
kind: Service
metadata:
  name: peer0-org1
  namespace: mediblock
spec:
  selector:
    app: peer0-org1
  ports:
  - name: peer-port
    port: 7051
    targetPort: 7051
  - name: operations
    port: 17051
    targetPort: 17051
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: peer0-org1
  namespace: mediblock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: peer0-org1
  template:
    metadata:
      labels:
        app: peer0-org1
    spec:
      volumes:
        - name: msp-volume
          configMap:
            name: peer0-org1-msp
        - name: msp-secret-volume
          secret:
            secretName: peer0-org1-msp-secret
        - name: empty-dir
          emptyDir: {}
      initContainers:
        - name: setup-folders
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - |
              mkdir -p /var/hyperledger/production/peer/msp/keystore && mkdir -p /var/hyperledger/production/peer/msp/cacerts && mkdir -p /var/hyperledger/production/peer/msp/signcerts && mkdir -p /var/hyperledger/production/peer/msp/admincerts && cp /msp-data/cacerts-ca.crt /var/hyperledger/production/peer/msp/cacerts/ca.crt && cp /msp-secret-data/peer.key /var/hyperledger/production/peer/msp/keystore/key.pem && cp /msp-data/signcerts-cert.pem /var/hyperledger/production/peer/msp/signcerts/cert.pem && cp /msp-data/admincerts-cert.pem /var/hyperledger/production/peer/msp/admincerts/cert.pem && chmod -R 777 /var/hyperledger/production
          volumeMounts:
            - name: msp-volume
              mountPath: /msp-data
            - name: msp-secret-volume
              mountPath: /msp-secret-data
            - name: empty-dir
              mountPath: /var/hyperledger/production
      containers:
        - name: peer0-org1
          image: hyperledger/fabric-peer:2.5.4
          ports:
            - containerPort: 7051
          env:
            - name: FABRIC_LOGGING_SPEC
              value: "debug"
            - name: CORE_PEER_ID
              value: "peer0-org1"
            - name: CORE_PEER_ADDRESS
              value: "peer0-org1:7051"
            - name: CORE_PEER_LISTENADDRESS
              value: "0.0.0.0:7051"
            - name: CORE_PEER_CHAINCODEADDRESS
              value: "peer0-org1:7052"
            - name: CORE_PEER_CHAINCODELISTENADDRESS
              value: "0.0.0.0:7052"
            - name: CORE_PEER_GOSSIP_BOOTSTRAP
              value: "peer0-org1:7051"
            - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
              value: "peer0-org1:7051"
            - name: CORE_PEER_LOCALMSPID
              value: "MediBlockMSP"
            - name: CORE_PEER_MSPCONFIGPATH
              value: "/var/hyperledger/production/peer/msp"
          volumeMounts:
            - name: empty-dir
              mountPath: /var/hyperledger/production 