apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderer
  namespace: mediblock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderer
  template:
    metadata:
      labels:
        app: orderer
    spec:
      volumes:
        - name: msp-volume
          configMap:
            name: orderer-msp
        - name: msp-secret-volume
          secret:
            secretName: orderer-msp-secret
        - name: empty-dir
          emptyDir: {}
        - name: genesis-volume
          configMap:
            name: fabric-genesis
        - name: config-dir
          emptyDir: {}
        - name: fabric-config-volume
          configMap:
            name: orderer-yaml-config
      initContainers:
        - name: setup-folders
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - |
              mkdir -p /var/hyperledger/production/orderer/msp/keystore && mkdir -p /var/hyperledger/production/orderer/msp/cacerts && mkdir -p /var/hyperledger/production/orderer/msp/signcerts && mkdir -p /var/hyperledger/production/orderer/msp/admincerts && cp /msp-data/cacerts-ca.crt /var/hyperledger/production/orderer/msp/cacerts/ca.crt && cp /msp-secret-data/key.pem /var/hyperledger/production/orderer/msp/keystore/key.pem && cp /msp-data/signcerts-cert.pem /var/hyperledger/production/orderer/msp/signcerts/cert.pem && cp /msp-data/admincerts-cert.pem /var/hyperledger/production/orderer/msp/admincerts/cert.pem && mkdir -p /var/hyperledger/fabric/config && cp /genesis-data/genesisblock /var/hyperledger/fabric/config/genesisblock && chmod -R 777 /var/hyperledger/production && chmod -R 777 /var/hyperledger/fabric
          volumeMounts:
            - name: msp-volume
              mountPath: /msp-data
            - name: msp-secret-volume
              mountPath: /msp-secret-data
            - name: empty-dir
              mountPath: /var/hyperledger/production
            - name: genesis-volume
              mountPath: /genesis-data
            - name: config-dir
              mountPath: /var/hyperledger/fabric
      containers:
        - name: orderer
          image: hyperledger/fabric-orderer:2.5.4
          command: ["orderer"]
          ports:
            - containerPort: 7050
          env:
            - name: FABRIC_LOGGING_SPEC
              value: "debug"
            - name: FABRIC_CFG_PATH
              value: "/etc/hyperledger/fabric"
          volumeMounts:
            - name: empty-dir
              mountPath: /var/hyperledger/production
            - name: config-dir
              mountPath: /var/hyperledger/fabric
            - name: fabric-config-volume
              mountPath: /etc/hyperledger/fabric 